# Base image: Ubuntu
FROM ubuntu:latest

# Update the system and install nginx
RUN apt-get update && apt-get install -y nginx

# Create two index.html files, one as .tar and another regular
RUN echo "<h1>Task2 index.html</h1>" > /var/www/html/index.html

# Create a tar archive with an index.html
RUN mkdir /tmp/web && echo "<h1>Hello from tarred index.html</h1>" > /tmp/web/index.html \
    && tar -czvf /var/www/html/index.tar -C /tmp/web index.html

# Expose port 80
EXPOSE 80

# Start nginx
CMD ["nginx", "-g", "daemon off;"]
